# Generated by Django 5.2.11 on 2026-07-09 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_user_role'),
        ('bloodinventor', '0005_expiryalert_alter_bloodbank_options_and_more'),
        ('donor', '0007_workflownotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcamp',
            name='destination_hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital that will receive blood collected at this camp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_camps', to='UserAuth.hospital'),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='total_collected_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampBloodCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField(default=1)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('collected', 'Collected at Camp'), ('in_transit', 'In Transit to Hospital'), ('received', 'Received at Hospital'), ('quality_check', 'Quality Check'), ('added_to_inventory', 'Added to Inventory'), ('rejected', 'Rejected (Quality Failed)')], default='collected', max_length=25)),
                ('transit_started_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('quality_checked_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_collections', to='donor.bloodcamp')),
                ('destination_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_camp_blood', to='UserAuth.hospital')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_blood_collections', to='donor.donordetails')),
                ('inventory_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_collection', to='bloodinventor.bloodinventory')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_camp_blood', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_collection', to='donor.campregistration')),
            ],
            options={
                'verbose_name': 'Camp Blood Collection',
                'verbose_name_plural': 'Camp Blood Collections',
                'ordering': ['-collected_at'],
            },
        ),
    ]
