title: "HopeDrop"
remote_theme: cepdnaclk/eYY-project-theme
description: "A centralized, digitized Blood Bank Management & Donation Tracking System for Sri Lanka"
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
