# Generated by Django 5.2.11 on 2026-07-09 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_user_role'),
        ('bloodinventor', '0004_bloodrequest_priority_level_and_more'),
        ('donor', '0007_workflownotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiring_soon', 'Expiring Soon (7 days)'), ('expiring_critical', 'Expiring Critical (3 days)'), ('expired', 'Expired')], max_length=20)),
                ('blood_type', models.CharField(max_length=3)),
                ('units_affected', models.PositiveIntegerField()),
                ('days_until_expiry', models.IntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_action', models.CharField(blank=True, choices=[('used', 'Used Before Expiry'), ('discarded', 'Discarded'), ('transferred', 'Transferred')], max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expiry Alert',
                'verbose_name_plural': 'Expiry Alerts',
                'ordering': ['days_until_expiry', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bloodbank',
            options={'verbose_name': 'Blood Bank', 'verbose_name_plural': 'Blood Banks'},
        ),
        migrations.AlterModelOptions(
            name='bloodinventory',
            options={'verbose_name': 'Blood Inventory', 'verbose_name_plural': 'Blood Inventories'},
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank', to='UserAuth.hospital'),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='expiry_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_inventory', to='UserAuth.hospital'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='source_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units', to='donor.bloodcamp'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='source_type',
            field=models.CharField(choices=[('camp', 'Blood Camp'), ('direct', 'Direct Donation'), ('transfer', 'Transfer')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodBankName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_banks', to='UserAuth.country'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_banks', to='UserAuth.district'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='postTalCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='registrationId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='blood_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='bloodinventor.bloodbank'),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('used', 'Used'), ('deleted', 'Deleted')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='bloodinventory',
            index=models.Index(fields=['hospital', 'blood_type', 'status'], name='idx_hospital_type_status'),
        ),
        migrations.AddIndex(
            model_name='bloodinventory',
            index=models.Index(fields=['expiry_date', 'status'], name='idx_expiry_status'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='UserAuth.hospital'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='bloodinventor.bloodinventory'),
        ),
    ]
